Update .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -47,7 +47,7 @@ matrix:
       compiler: clang
       addons:
         apt:
-          packages: libboost_unit_test_framework-dev
+          packages: libboost-all-dev
 
     
 install:
@@ -68,24 +68,24 @@ install:
   ############################################################################
   # Install Boost headers
   ############################################################################
-  - |
-    if [[ "${BOOST_VERSION}" != "" ]]; then
-      BOOST_DIR=${DEPS_DIR}/boost-${BOOST_VERSION}
-      if [[ -z "$(ls -A ${BOOST_DIR})" ]]; then
-        if [[ "${BOOST_VERSION}" == "trunk" ]]; then
-          BOOST_URL="http://github.com/boostorg/boost.git"
-          travis_retry git clone --depth 1 --recursive --quiet ${BOOST_URL} ${BOOST_DIR} || exit 1
-          (cd ${BOOST_DIR} && ./bootstrap.sh && ./b2 headers)
-        else
-          BOOST_URL="http://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION}/boost_${BOOST_VERSION//\./_}.tar.gz"
-          mkdir -p ${BOOST_DIR}
-          { travis_retry wget --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${BOOST_DIR}; } || exit 1
-        fi
+  #- |
+  #  if [[ "${BOOST_VERSION}" != "" ]]; then
+  #    BOOST_DIR=${DEPS_DIR}/boost-${BOOST_VERSION}
+  #    if [[ -z "$(ls -A ${BOOST_DIR})" ]]; then
+  #      if [[ "${BOOST_VERSION}" == "trunk" ]]; then
+  #        BOOST_URL="http://github.com/boostorg/boost.git"
+  #        travis_retry git clone --depth 1 --recursive --quiet ${BOOST_URL} ${BOOST_DIR} || exit 1
+  #        (cd ${BOOST_DIR} && ./bootstrap.sh && ./b2 headers)
+  #      else
+  #        BOOST_URL="http://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION}/boost_${BOOST_VERSION//\./_}.tar.gz"
+  #        mkdir -p ${BOOST_DIR}
+  #        { travis_retry wget --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${BOOST_DIR}; } || exit 1
+  #      fi
         # Make sure we don't conflict with the Hana shipped with Boost
-        rm -rf ${BOOST_ROOT}/include/boost/{hana,hana.hpp}
-      fi
-      CMAKE_OPTIONS+=" -DBOOST_ROOT=${BOOST_DIR}"
-    fi
+  #      rm -rf ${BOOST_ROOT}/include/boost/{hana,hana.hpp}
+  #    fi
+  #    CMAKE_OPTIONS+=" -DBOOST_ROOT=${BOOST_DIR}"
+  #  fi
 
   ############################################################################
   # Install a recent CMake
@@ -103,11 +103,11 @@ install:
   ############################################################################
   # Install Boost.Build
   ############################################################################
-  - |
-    if [[ "${BOOST_BUILD}" == "true" ]]; then
-      (cd ${BOOST_DIR}/tools/build && ./bootstrap.sh && ./b2 install --prefix=${DEPS_DIR}/b2)
-      export PATH=${DEPS_DIR}/b2/bin:${PATH}
-    fi
+  #- |
+  #  if [[ "${BOOST_BUILD}" == "true" ]]; then
+  #    (cd ${BOOST_DIR}/tools/build && ./bootstrap.sh && ./b2 install --prefix=${DEPS_DIR}/b2)
+  #    export PATH=${DEPS_DIR}/b2/bin:${PATH}
+  #  fi
 
   ############################################################################
   # Install Clang, libc++ and libc++abi
@@ -149,17 +149,4 @@ before_script:
 
 
 script:
-
-  ############################################################################
-  # Build and run the unit tests and examples.
-  ############################################################################
-
-  - |
-    if [[ "${UNIT_TESTS}" == "true" && "${BOOST_BUILD}" != "true" ]]; then
-      (cd build && make tests -j2 -k) &&
-      if [[ "${ENABLE_MEMCHECK}" == "true" ]]; then
-        (cd build && ctest --output-on-failure -j2 -D ExperimentalMemCheck)
-      else
-        (cd build && ctest --output-on-failure -j2)
-      fi
-    fi
+  - cd ${TRAVIS_BUILD_DIR} && tools/test
